### ISSUE TITLE
Mixin Crash

### ISSUE THREAD

**Issue by Mattabase** [AlmostReliable/lootjs#8]
### Version

lootjs-fabric-1.19.2-2.7.5.jar

### Crash Report

https://gist.github.com/ffecfa4f03c2cc84899d087f035dd329

### Additional Context

Yes

### Modifications

Repurposed Structures 

![image](https://user-images.githubusercontent.com/2126947/197359245-b5f3ae61-f87b-40d0-84eb-92766181ef22.png)

![image](https://user-images.githubusercontent.com/2126947/197359257-c089f52e-2aba-45fa-b753-aaf7a3adfc12.png)

https://github.com/TelepathicGrunt/RepurposedStructures/blob/70bee0f26aa633c7543dcaacf0f595bdf2758a04/src/main/java/com/telepathicgrunt/repurposedstructures/misc/lootmanager/StructureModdedLootImporter.java#L272

https://shartte.github.io/minecraft-mapper/

### Did the crash happen in singleplayer or on a server?

Both

**Comment by TelepathicGrunt** [comment]
To the LootJS dev, I am the dev for repurposed structures. Let me know if there’s anything I am doing incorrectly on my end. But in order to roll another loot table within my mixin, I have to get a new loot context as iirc, there way something that prevented me from reusing the current one or some sort of infinite recursion or something. Is there a more preferred way of making a copy of a loot context?

**Comment by TelepathicGrunt** [comment]
Fixed in v6.1.2 Fabric RS and fixed in v6.3.3 Quilt RS. Uses putAll now instead to keep original mutable maps.
![image](https://user-images.githubusercontent.com/40846040/197394811-ed39b18e-0e3d-4072-b509-2682d10b6e4c.png)

And i just realized my commits spammed this github... oops

**Comment by LLytho** [comment]
@TelepathicGrunt Thank you!
